### PR TITLE
Feature - Implement fine grained permission control for "cluster:admin/snapshot/restore"

### PR DESCRIPTION
**Pull request by breml**
This PR implements the fine grained permission control for `cluster:admin/snapshot/restore` as extension of the work in https://github.com/floragunncom/search-guard/pull/245. This extension was already outlined in the before mentioned PR.

I would very much appreciate your feedback to this proposal / implementation.

# Implementation

The current implementation allows a snapshot restore operation only, if the following conditions are met:

1. User has the snapshot restore privilege (`cluster:admin/snapshot/restore`)
2. User has the below listed rights for all types (`*`) on the target index:
    * `indices:admin/create`
    * `indices:data/write/index`

For the definition of the required permissions to perform a restore, I see two approaches:

1. Make the list hard coded in SearchGuard (the way it is done at the moment)
2. Make the list of the required permissions on the indices configurable

I am open to discussion.

# Configuration

The whole functionality may be disabled using the following configuration:

```
searchguard.check_snapshot_restore_write_privileges: false
```

# Future development

With the fine grained permission control in place for the snapshot restore feature, the same should be implemented for snapshot create (`cluster:admin/snapshot/create`) for this functionality to be feature complete. In this case, a user who wants to create a snapshot does need to have the following permissions:

1. Permission to create a snapshot `cluster:admin/snapshot/create`
2. Permission to read all indices, which are selected for the snapshot. The following permissions should be hold by the user on every type (`*`) within the index (final list to be defined):
    * `indices:data/read/exists`
    * `indices:data/read/get`
    * maybe `indices:data/read/mget`
    * maybe `indices:data/read/scroll`

### CODE REVIEW

**Comment by breml** [comment]
I have signed the CLA last week, hopefully we can now go forward with this PR.

**Comment by floragunncom** [comment]
Will start work on this PR and https://github.com/floragunncom/search-guard/pull/245 soon

**Comment by floragunncom** [comment]
I have merged #245 into https://github.com/floragunncom/search-guard/tree/breml-feature-user-restore. This PR (#257) breaks compatibility by altering the (now/meanwhile public) PrivilegesEvaluator.IndexType class. It would be necessary to either rebase this PR onto https://github.com/floragunncom/search-guard/tree/breml-feature-user-restore and find a solution to avoid altering the PrivilegesEvaluator.IndexType class. Can you do this @breml ?

**Comment by breml** [comment]
@floragunncom I will try to have a look at this in the next view days, but currently I can not promise anything, as I am working on other topics right now.

**Comment by breml** [comment]
@floragunncom Unfortunately I did not yet find the time to update the PR. I hope, I will find the time in week 11.

**Comment by floragunncom** [comment]
@breml Why is a restore of the global state not allowed?

**Comment by breml** [comment]
Because this PR implements the verification of specific rights on indices (indices:admin/create
indices:data/write/index). The global state would therefore need an additional right which could be granted to an user, if it should be possible at all. In my opinion, a restore of the global state should always be an operation performed by an admin user.

**Comment by floragunncom** [comment]
thx and +1

**Comment by breml** [comment]
Merged this PR with branch https://github.com/floragunncom/search-guard/tree/breml-feature-user-restore as suggested in https://github.com/floragunncom/search-guard/pull/257#issuecomment-281176706 and created a new PR #311.

**Comment by floragunncom** [comment]
merged https://github.com/floragunncom/search-guard/pull/311 so this PR is obsolete now

**Pull request closed without merging**
