### PR TITLE
Refactoring abstraction over configuration

### PR DESCRIPTION
**Pull request by Gordiychuk**
Refactoring include:
- Remove unsafe reference publication via `com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction#addConfigChangeListener`
- Reduce count dependency for `com.floragunn.searchguard.auth.BackendRegistry` that simplify it class
- Documentation for configuration abstraction
- Fix potential bug, when notify backed occurs in random order - for example authenticator or auth backend can depends on some configuration, server try reload configs, notify about changes athentication or auth backend and then notify about changes BackendRegistry. BackendRegistry recreate authentication domain with new instance authenticator and auth backend, they not initialize, because notification already apply on previous instance, as result server in not valid state. 

As you can see, was change logic initial initialize - if searchguard index not exists, or doesn't have some required configuration not necessary wait, when configuration will be create because after modify or add configuration, sgadmin will execute ConfigUpdateAction and config will be reload.

### CODE REVIEW

**Comment by Gordiychuk** [comment]
I also add new dependency on jsr305 that introduce `@Nullable`, `@Nonull` that allow IDE notify about potential NPE and also provides good API describe

**Comment by Gordiychuk** [comment]
I decided split big PR with oauth integration on few independens PR to simplify review

**Comment by floragunncom** [comment]
This will be included in the upcoming 5.2 compatible release

**Comment by floragunncom** [comment]
incorporated with https://github.com/floragunncom/search-guard/commit/ca2dc38815c1f28271b7e047c6e9c66012a33dec

Thanks for this contribution, great work 👍

**Pull request closed without merging**
