### PR TITLE
Logstash needs cluster:monitor/main permissions

### PR DESCRIPTION
**Pull request by matejzero**
It looks like logstash (at least 5.1.1, but more likely the whole 5.x branch) needs cluster:monitor/main for successful start (probably because of the [healthcheck]( https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-healthcheck_path).

### CODE REVIEW

**Comment by floragunncom** [comment]
@matejzero does this look good for you? -> https://github.com/floragunncom/search-guard/commit/5a42fd8ff32606250f97673da7e774fbf37bc435

**Comment by floragunncom** [comment]
Thanks for signing the CLA

**Comment by matejzero** [comment]
No problem, thanks for great software:)

**Comment by floragunncom** [comment]
would be great if you can close the two PR's, its much easier for me in terms of merging :-)

**Comment by matejzero** [comment]
Consider it done:)

**Pull request closed without merging**
