### PR TITLE
Kibana (at least 5.1.1) needs CLUSTER_MONITOR permission to work

### PR DESCRIPTION
**Pull request by matejzero**
…eed an additional cluster:monitor/main permission. We could probably simplify it and just give it the whole CLUSTER_MONITOR (looking at Shield's roles, they assign monitor permissions to kibana server)

### CODE REVIEW

**Comment by matejzero** [comment]
Where can I sign CLA?

**Comment by floragunncom** [comment]
CLA setup almost finished, we notify you when we are ready

**Comment by matejzero** [comment]
I don't mind if you reject the pull request and do the fix yourself:) Would rather see the problem fixed, so someone else wouldn't need to figure the same problem out.

**Comment by matejzero** [comment]
Closing in favor of 5a42fd8

**Pull request closed without merging**
