### PR TITLE
Feature - Implement evaluation of "cluster:admin/snapshot/restore" permission (allow snapshot for normal users)

### PR DESCRIPTION
**Pull request by breml**
# Introduction
A while ago I asked about this feature in the [Google Groups](https://groups.google.com/forum/#!msg/search-guard/4PSo8UW55DY/Fn8batR5BQAJ). Because this is still an important use-case for use, we decided to implement this feature to allow a better discussion about this. The main problem in our case is, that we can not provide the user full admin access to Elasticsearch but we still want to allow the user to create and restore snapshots of the indices.

I would very much appreciate your feedback to this proposal / implementation.

# Implementation in this PR
This PR implements the evaluation of the permission `cluster:admin/snapshot/restore` in a global manner, which means, if a user has this permission, he is allowed to restore every index with the exception of the protected `searchguard` index.

# Details about the implementation
Currently the whole evaluation logic for the `cluster:admin/snapshot/restore` permission is put into its own function called `evaluateSnapshotRestore`. It is heavily inspired by the function `evaluate` but implements the special handling for the index names in the snapshot as well as the rename handling (`rename_pattern`, `rename_replacement`).
If this merge request is accepted in general, we could think about some optimizations to remove some of the duplicated code.

# Details about the commits
In the [first commit](https://github.com/floragunncom/search-guard/commit/919b7b68275eb6427eb292feeba257c1f3975734) I just implemented a few tests, which ensure the behavior of SearchGuard prior to this PR.
The second commit implements the functionality to make `cluster:admin/snapshot/restore` work with the exception of the `searchguard` index, which is not allowed as source and as destination index.
The third commit adds the possibility to opt-in for this functionality while preserving the old behavior by default (adds the configuration option `searchguard.enable_snapshot_restore_privilege`).
The last commit prevents the snapshot restore operation, if the requests also wants to restore the global state (Elasticsearch cluster state).

I was unsure from which branch I should fork because first I thought I will need some of the features, which are only provided by Elasticsearch 5.0.x. That's why I forked from the `es-5.0.0` branch.

# Future development
Currently I am thinking about an extended version of the behavior for the snapshot restore feature. The extended version would have the following functionality:
A snapshot restore operation is only allowed, if the user has the general `cluster:admin/snapshot/restore` right and additional the following rights on every index (and on every type: `'*'`) he wants to restore (final list to be defined):
* `indices:admin/create`
* `indices:data/write/index`
* maybe `indices:data/write/bulk`

This would allow for fine grained control of the snapshot restore permission as it would be limited to the same restrictions, the user has for normal index creation and document indexing.

### CODE REVIEW

**Comment by floragunncom** [comment]
thx a lot, we will have a look ...

**Comment by breml** [comment]
I have signed the CLA last week, hopefully we can now go forward with this PR.

**Comment by floragunncom** [comment]
Will now start working on this.

**Comment by floragunncom** [comment]
merged https://github.com/floragunncom/search-guard/pull/311 so this PR is obsolete now

**Pull request closed without merging**
