### PR TITLE
Remove unneeded dependency on NettyRequest

### PR DESCRIPTION
**Pull request by jcantrill**
This PR removes the dependency on Netty4HttpRequest in XFFResolver which is not required.

### CODE REVIEW

**Comment by floragunncom** [comment]
@jcantrill thx

Can you pls also remove the org.elasticsearch.http.netty4.Netty4HttpRequest import?

**Comment by jcantrill** [comment]
@floragunncom done

**Comment by floragunncom** [comment]
thx, pls. also for XFFResolver.java

**Comment by jcantrill** [comment]
@floragunncom done

**Comment by jcantrill** [comment]
@floragunncom bump...  possible to get this merged and released into a 5.6.10 release?

**Comment by floragunncom** [comment]
This will be merged soon and we can also prepare a 5.6.10 release. Thanks!

**Comment by floragunncom** [comment]
Search Guard 5.6.10-19.2 is released

**Pull request merged**
